#!/usr/bin/env python3
"""Build a pg_regress schedule for a named subset of the core regression tests.

The subset is expressed as a plain list of test names.  Rather than invent an
ordering, this filters src/test/regress/parallel_schedule in place: every
`test: a b c` line is reduced to the members of the subset, preserving the
upstream order and the upstream parallel grouping, and empty groups are
dropped.  That matters because a fair number of core tests only work in the
group upstream put them in (test_setup first, create_index before its
consumers, sanity_check's VACUUM before the tests whose expected output
depends on the resulting heap order, tablespace last).

Fails loudly if a subset entry is not a test in the schedule, or has no
sql/<name>.sql -- a silently dropped test is a silently weakened gate.
"""

import argparse
import os
import sys


def parse_subset(path):
    names = []
    with open(path) as f:
        for line in f:
            line = line.split('#', 1)[0].strip()
            if not line:
                continue
            names.extend(line.split())
    seen = set()
    dups = [n for n in names if n in seen or seen.add(n)]
    if dups:
        sys.exit("gen_schedule: duplicate test(s) in %s: %s" %
                 (path, ' '.join(sorted(set(dups)))))
    return names


def parse_schedule(path):
    """Return [(kind, payload)] where kind is 'test' or 'raw'."""
    out = []
    with open(path) as f:
        for line in f:
            stripped = line.rstrip('\n')
            if stripped.startswith('test: '):
                out.append(('test', stripped[len('test: '):].split()))
            else:
                out.append(('raw', stripped))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--regress-src', required=True,
                    help='src/test/regress of the tree the server was built from')
    ap.add_argument('--subset', required=True, help='subset file')
    ap.add_argument('--out', required=True, help='schedule file to write')
    ap.add_argument('--print-groups', action='store_true')
    args = ap.parse_args()

    schedule_path = os.path.join(args.regress_src, 'parallel_schedule')
    subset = parse_subset(args.subset)
    entries = parse_schedule(schedule_path)

    known = set()
    for kind, payload in entries:
        if kind == 'test':
            known.update(payload)

    unknown = [n for n in subset if n not in known]
    if unknown:
        sys.exit("gen_schedule: not present in %s: %s" %
                 (schedule_path, ' '.join(unknown)))

    missing = [n for n in subset
               if not os.path.exists(os.path.join(args.regress_src, 'sql', n + '.sql'))]
    if missing:
        sys.exit("gen_schedule: no sql/<test>.sql for: %s" % ' '.join(missing))

    want = set(subset)
    groups = []
    emitted = set()
    for kind, payload in entries:
        if kind != 'test':
            continue
        keep = [t for t in payload if t in want]
        if keep:
            groups.append(keep)
            emitted.update(keep)

    # Cannot happen given the checks above, but assert it rather than trust it.
    lost = want - emitted
    if lost:
        sys.exit("gen_schedule: internal error, dropped %s" % ' '.join(sorted(lost)))

    with open(args.out, 'w') as f:
        f.write('# Generated by gen_schedule.py -- do not edit.\n')
        f.write('# subset:   %s\n' % os.path.abspath(args.subset))
        f.write('# schedule: %s\n' % schedule_path)
        f.write('# %d tests in %d parallel groups\n' % (len(emitted), len(groups)))
        for g in groups:
            f.write('test: %s\n' % ' '.join(g))

    if args.print_groups:
        print('%d tests in %d groups:' % (len(emitted), len(groups)))
        for i, g in enumerate(groups, 1):
            print('  %2d. %s' % (i, ' '.join(g)))


if __name__ == '__main__':
    main()
