--
-- src/test/memcow/seed/schema.sql
--
-- Schema + data for the memcow ephemeral-test-engine seed cluster.
--
-- This file is applied by build_seed.sh to template1 *before* the lane
-- databases are created, so every lane starts from byte-identical relation
-- files.  It is plain DDL/DML only: no VACUUM, no CHECKPOINT, no CREATE
-- DATABASE (build_seed.sh owns those, because VACUUM cannot run inside the
-- single transaction psql -1 would wrap this in, and because the freeze pass
-- has to cover the lane databases too).
--
-- Design constraints, from plan.md:
--
--   * §7.1 workload set: DDL, DML, vacuum, sequences, temp tables, COPY,
--     index builds.  The objects below are chosen to give each of those
--     something real to chew on.
--   * "enough rows that relations span more than one page": every seeded
--     heap below is > 4 pages, which is also the threshold at which VACUUM
--     bothers to create an FSM fork (HEAP_FSM_CREATION_THRESHOLD), so the
--     seed ends up exercising main/fsm/vm forks rather than main alone.
--   * DETERMINISM IS LOAD-BEARING.  §7.2 loops "reset -> seed-hash verify +
--     differential query" 10,000 times, so the seed's contents must be a pure
--     function of the schema file.  Therefore: no random(), no now()/
--     clock_timestamp(), no OID-order-dependent data.  All generated values
--     derive from generate_series and md5(), and all timestamps are offsets
--     from a fixed absolute instant.
--   * Small and fast: the whole thing is a couple of seconds and a few MB per
--     database.  The seed is mmapped read-only at runtime, so its size costs
--     address space and lazy page-ins, not RAM-disk budget -- but it is
--     copied once per lane, so keep it modest.
--

\set ON_ERROR_STOP on

-- ---------------------------------------------------------------------------
-- accounts: heap + PK + unique index + composite index + expression index.
-- 5,000 rows, ~60 pages.
-- ---------------------------------------------------------------------------

CREATE TABLE public.accounts (
    account_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login        text          NOT NULL,
    display_name text          NOT NULL,
    status       text          NOT NULL,
    balance      numeric(14,2) NOT NULL,
    created_at   timestamptz   NOT NULL
);

INSERT INTO public.accounts
        (account_id, login, display_name, status, balance, created_at)
SELECT  i,
        'user' || i,
        'Account ' || md5(i::text),
        (ARRAY['active', 'idle', 'closed'])[1 + (i % 3)],
        ((i % 99991)::numeric) / 100,
        TIMESTAMPTZ '2020-01-01 00:00:00+00' + (i * INTERVAL '17 minutes')
FROM    generate_series(1, 5000) AS i;

-- Identity column: leave the sequence positioned past the seeded rows, so a
-- test's first INSERT does not collide.  Also gives the reset loop a sequence
-- whose non-reverted advancement is one of the Appendix C "provably benign"
-- monotonic items.
SELECT setval(pg_get_serial_sequence('public.accounts', 'account_id'), 5000, true);

CREATE UNIQUE INDEX accounts_login_key ON public.accounts (login);
CREATE INDEX accounts_status_created_at_idx ON public.accounts (status, created_at);
CREATE INDEX accounts_display_name_lower_idx ON public.accounts (lower(display_name));

-- ---------------------------------------------------------------------------
-- ledger: a standalone sequence (not an identity/serial), an FK back to
-- accounts (so the reset loop exercises RI triggers and catcache entries for
-- constraint lookups), and enough rows to be genuinely multi-page.
-- 20,000 rows, ~200 pages.
-- ---------------------------------------------------------------------------

CREATE SEQUENCE public.ledger_entry_no_seq
    START WITH 1 INCREMENT BY 1 CACHE 1;

CREATE TABLE public.ledger (
    entry_no   bigint        PRIMARY KEY
                             DEFAULT nextval('public.ledger_entry_no_seq'),
    account_id bigint        NOT NULL REFERENCES public.accounts(account_id),
    posted_at  timestamptz   NOT NULL,
    amount     numeric(14,2) NOT NULL,
    memo       text          NOT NULL
);

INSERT INTO public.ledger (account_id, posted_at, amount, memo)
SELECT  1 + (i % 5000),
        TIMESTAMPTZ '2021-06-01 00:00:00+00' + (i * INTERVAL '3 minutes'),
        (((i % 20011) - 10000)::numeric) / 100,
        'entry ' || i || ' ' || md5((i * 7)::text)
FROM    generate_series(1, 20000) AS i;

CREATE INDEX ledger_account_id_posted_at_idx
    ON public.ledger (account_id, posted_at);

-- ---------------------------------------------------------------------------
-- documents: the TOAST case.  body is SET STORAGE EXTERNAL, so the ~9.6 kB
-- values are pushed out of line *without* compression -- guaranteeing a
-- populated, multi-page TOAST relation and its TOAST index rather than
-- relying on a compression ratio.  meta gets a GIN index so the seed contains
-- at least one non-btree access method (different page layout, metapage,
-- pending list) for memcow's page paths to survive.
-- 250 rows, ~2.4 MB of TOAST.
-- ---------------------------------------------------------------------------

CREATE TABLE public.documents (
    doc_id int   PRIMARY KEY,
    title  text  NOT NULL,
    meta   jsonb NOT NULL,
    body   text  NOT NULL
);

ALTER TABLE public.documents ALTER COLUMN body SET STORAGE EXTERNAL;

INSERT INTO public.documents (doc_id, title, meta, body)
SELECT  i,
        'Document ' || i,
        jsonb_build_object('kind', (ARRAY['note','spec','memo'])[1 + (i % 3)],
                           'rank', i % 11,
                           'tags', to_jsonb(ARRAY['t' || (i % 5), 't' || (i % 7)])),
        repeat(md5(i::text), 300)
FROM    generate_series(1, 250) AS i;

CREATE INDEX documents_meta_idx ON public.documents USING gin (meta jsonb_path_ops);

-- ---------------------------------------------------------------------------
-- events: the COPY target.  Deliberately index-light and constraint-free so
-- COPY tests measure COPY, and pre-seeded past the one-page mark so that a
-- COPY lands on top of existing content (mixed seed/overlay block vectors,
-- §7.1) rather than into an empty relation.
-- 4,000 rows, ~45 pages.
-- ---------------------------------------------------------------------------

CREATE TABLE public.events (
    event_id    bigint      NOT NULL,
    account_id  bigint      NOT NULL,
    kind        text        NOT NULL,
    occurred_at timestamptz NOT NULL,
    payload     jsonb
);

INSERT INTO public.events (event_id, account_id, kind, occurred_at, payload)
SELECT  i,
        1 + (i % 5000),
        (ARRAY['login','logout','purchase','refund'])[1 + (i % 4)],
        TIMESTAMPTZ '2022-03-01 00:00:00+00' + (i * INTERVAL '11 minutes'),
        jsonb_build_object('seq', i, 'hash', md5(i::text))
FROM    generate_series(1, 4000) AS i;

CREATE INDEX events_account_id_idx ON public.events (account_id);

-- ---------------------------------------------------------------------------
-- staging: UNLOGGED, which is the only cheap way to get an INIT_FORKNUM
-- relation into the seed.  memcow has to resolve the init fork through the
-- same overlay/seed path as main/fsm/vm, and an unlogged relation is also the
-- one thing a clean shutdown must NOT truncate (a crash would).  Small on
-- purpose -- it exists for fork coverage, not data volume.
-- ---------------------------------------------------------------------------

CREATE UNLOGGED TABLE public.staging (
    staging_id  int  PRIMARY KEY,
    raw_line    text NOT NULL
);

INSERT INTO public.staging (staging_id, raw_line)
SELECT i, 'raw ' || md5((i * 13)::text)
FROM   generate_series(1, 1000) AS i;

-- ---------------------------------------------------------------------------
-- A view and a PL/pgSQL function: plancache and PL global state are named in
-- Appendix C as things DISCARD ALL does not reset, so the seed must contain
-- something that actually populates them.
-- ---------------------------------------------------------------------------

CREATE VIEW public.account_balances AS
SELECT  a.account_id,
        a.login,
        a.status,
        coalesce(sum(l.amount), 0)::numeric(14,2) AS ledger_total,
        count(l.entry_no)                         AS entry_count
FROM    public.accounts a
        LEFT JOIN public.ledger l USING (account_id)
GROUP BY a.account_id, a.login, a.status;

CREATE FUNCTION public.account_total(p_account_id bigint)
RETURNS numeric
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_total numeric;
BEGIN
    SELECT coalesce(sum(amount), 0) INTO v_total
    FROM   public.ledger
    WHERE  account_id = p_account_id;

    RETURN v_total;
END;
$$;

-- ---------------------------------------------------------------------------
-- A stable digest the reset loop (§7.2 "seed-hash verify") can compare across
-- epochs without hand-writing the query each time.  It is a view, not a
-- materialization, so it costs the seed nothing.
-- ---------------------------------------------------------------------------

CREATE VIEW public.memcow_seed_digest AS
SELECT 'accounts'::text  AS relname, count(*) AS nrows,
       md5(string_agg(t.txt, E'\n' ORDER BY t.txt)) AS digest
FROM  (SELECT a.account_id || '|' || a.login || '|' || a.status || '|' || a.balance AS txt
       FROM public.accounts a) t
UNION ALL
SELECT 'ledger', count(*),
       md5(string_agg(t.txt, E'\n' ORDER BY t.txt))
FROM  (SELECT l.entry_no || '|' || l.account_id || '|' || l.amount AS txt
       FROM public.ledger l) t
UNION ALL
SELECT 'documents', count(*),
       md5(string_agg(t.txt, E'\n' ORDER BY t.txt))
FROM  (SELECT d.doc_id || '|' || md5(d.body) || '|' || d.meta::text AS txt
       FROM public.documents d) t
UNION ALL
SELECT 'events', count(*),
       md5(string_agg(t.txt, E'\n' ORDER BY t.txt))
FROM  (SELECT e.event_id || '|' || e.kind || '|' || e.payload::text AS txt
       FROM public.events e) t
UNION ALL
SELECT 'staging', count(*),
       md5(string_agg(t.txt, E'\n' ORDER BY t.txt))
FROM  (SELECT s.staging_id || '|' || s.raw_line AS txt
       FROM public.staging s) t;

COMMENT ON VIEW public.memcow_seed_digest IS
    'Deterministic content digest of the memcow seed relations; compared '
    'across lane epochs by the §7.2 reset loop.';
